name: CI

on: [push, pull_request]

jobs:
    check:
        name: Check
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        steps:
        - uses: actions/checkout@v1
        - name: Setup PHP with composer v2
          uses: shivammathur/setup-php@v2
          with:
              php-version: '8.2'
              tools: composer
        -
          name: Install dependencies
          run: composer install -o
        -
          name: CI checks
          run: vendor/bin/phpbench run tests/Benchmark --report=default --revs 100000

